<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="f45c899d4237" ignored="0" name="Test" tests="11" failures="4" timestamp="11 Mar 2018 03:32:16 GMT" time="0.051" errors="0">
  <testcase name="hasTablePractice" time="0.009" classname="com.harsha.javaPractice.collections.day12.HashTableExample"/>
  <testcase name="arrayListExample" time="0.001" classname="com.harsha.javaPractice.collections.day12.ArrayListPractice"/>
  <testcase name="iteratorPractice" time="0.001" classname="com.harsha.javaPractice.collections.day12.IteratorPractice"/>
  <testcase name="stackPractice" time="0.001" classname="com.harsha.javaPractice.collections.day12.StackExample"/>
  <testcase name="arrayIndexOutOfBoundExceptionPractice" time="0.001" classname="com.harsha.javaPractice.Exceptions.day7.ExceptionHandling"/>
  <testcase name="fileNotFoundExceptionHandlingPractice" time="0.001" classname="com.harsha.javaPractice.Exceptions.day7.ExceptionHandling">
    <failure type="java.io.FileNotFoundException" message="G:/Eclipse/Workspace (No such file or directory)">
      <![CDATA[java.io.FileNotFoundException: G:/Eclipse/Workspace (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at com.harsha.javaPractice.Exceptions.day7.ExceptionHandling.fileNotFoundExceptionHandlingPractice(ExceptionHandling.java:32)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- fileNotFoundExceptionHandlingPractice -->
  <testcase name="nullPointerExceptionPractice" time="0.002" classname="com.harsha.javaPractice.Exceptions.day7.ExceptionHandling">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.harsha.javaPractice.Exceptions.day7.ExceptionHandling.nullPointerExceptionPractice(ExceptionHandling.java:48)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- nullPointerExceptionPractice -->
  <testcase name="throwNewExceptionPractice" time="0.001" classname="com.harsha.javaPractice.Exceptions.day7.ExceptionHandling">
    <failure type="java.lang.Exception" message="This is my exception and its been designed by me !!!!">
      <![CDATA[java.lang.Exception: This is my exception and its been designed by me !!!!
	at com.harsha.javaPractice.Exceptions.day7.ExceptionHandling.throwNewExceptionPractice(ExceptionHandling.java:66)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- throwNewExceptionPractice -->
  <testcase name="tryCatchBlockExample" time="0.0" classname="com.harsha.javaPractice.Exceptions.day7.ExceptionHandling"/>
  <testcase name="tryCatchExceptionPractice" time="0.0" classname="com.harsha.javaPractice.Exceptions.day7.ExceptionHandling">
    <failure type="java.lang.Exception" message="This is my exception and its been designed by me !!!!">
      <![CDATA[java.lang.Exception: This is my exception and its been designed by me !!!!
	at com.harsha.javaPractice.Exceptions.day7.ExceptionHandling.tryCatchExceptionPractice(ExceptionHandling.java:78)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- tryCatchExceptionPractice -->
  <testcase name="tryCatchFinallyBlockPractice" time="0.001" classname="com.harsha.javaPractice.Exceptions.day7.ExceptionHandling"/>
</testsuite> <!-- Test -->
